"""
This script takes in the "random_sample" CSV file generated by random_sample.py 
and finds the corresponding MRI files for each selected patient. The output is
a new CSV file formatted for use with the OASIS retrieval scripts.
"""

import os
import pandas as pd

BASEDIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RANDOM_SAMPLE_CSV_PATH = os.path.join(BASEDIR, "oasis-files", "processed", "random_sample.csv")
OASIS_MRI_PATH = os.path.join(BASEDIR, "oasis-files", "OASIS3_MR_json.csv")
OUTPUT_DIR = os.path.join(BASEDIR, "oasis-files", "scripts")
TO_GET_MRI = 5

def find_mri_files(random_sample_csv_path, oasis_data_path, output_csv_path):
    random_sample_df = pd.read_csv(random_sample_csv_path)
    oasis_df = pd.read_csv(oasis_data_path)

    # Create a mapping of subject_id to their MRI file labels
    labels_map = oasis_df.groupby("subject_id")["label"].apply(list).to_dict()

    # Merge dataframes to find corresponding MRI files
    patient_ids = random_sample_df["subject_id"].tolist()



    mri_files = []
    while patient_ids:
        id = patient_ids.pop(0)
        label = labels_map.get(id)
        if label:
            mri_files.append(label.pop(0))
            if not label:
                labels_map.pop(id)
        else:
            print(f"No MRI files found for subject_id: {id}")


    random_sample_df["mri_file"] = mri_files

    mri_files = pd.DataFrame(mri_files)

    # Save to new CSV file
    os.makedirs(output_csv_path, exist_ok=True)
    mri_output_file_path = os.path.join(output_csv_path, "oasis_data_for_scripts.csv")
    key_output_file_path = os.path.join(output_csv_path, "patient_mri_keys.csv")
    pd.DataFrame(mri_files).to_csv(mri_output_file_path, index=False, header=False)
    pd.DataFrame(random_sample_df).to_csv(key_output_file_path, index=False)

if __name__ == "__main__":
    find_mri_files(RANDOM_SAMPLE_CSV_PATH, OASIS_MRI_PATH, OUTPUT_DIR)
    print("MRI files have been successfully matched and saved.\n")
    print("Please use 'oasis_data_for_scripts.csv' for the OASIS retrieval scripts.\n")
    print("Use the following format:\n")
    print("---------------------------------------------------\n")
    print("./download_oasis_scans_bids.sh oasis_data_for_scripts.csv <output_directory> <nitrc_ir_username> T1w\n")
    print("---------------------------------------------------\n")
