import os
import pandas as pd

"""
This script takes in the CSV file generated by parse_oasis_data.py and randomly
selectes a predetermined number of patients from each category (Cognitively Normal
and AD Dementia). The selected patients are then saved into a new CSV file for
use in the OASIS retrieval scripts.

https://github.com/NrgXnat/oasis-scripts

"""

BASEDIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PARSED_CSV_PATH = os.path.join(BASEDIR, "oasis-files", "processed", "parsed_oasis_data.csv")
OUTPUT_DIR = os.path.join(BASEDIR, "oasis-files", "processed")
NUM_SAMPLES_PER_GROUP = 5

def random_sample_oasis_data(parsed_csv_path, output_csv_path, num_samples_per_group):
    df = pd.read_csv(parsed_csv_path)

    # Separate cognitively normal and AD patients
    cognitively_normal = df[df['dx1'] == 'Cognitively normal']
    ad_patients = df[df['dx1'] == 'AD Dementia']

    # Randomly sample patients from each group
    sampled_cognitively_normal = cognitively_normal.sample(n=min(num_samples_per_group, len(cognitively_normal)), random_state=27)
    sampled_ad_patients = ad_patients.sample(n=min(num_samples_per_group, len(ad_patients)), random_state=27)
    sampled_df = pd.concat([sampled_cognitively_normal, sampled_ad_patients])

    csv_rows = []
    for line in sampled_df.itertuples(index=False):
        csv_rows.append({
            "experiment_id": line.OASIS_session_label,
            "diagnosis": line.dx1,
            "subject_id": line.OASISID
        })

    csv_data = pd.DataFrame(csv_rows)

    # Save to new CSV file
    os.makedirs(output_csv_path, exist_ok=True)
    csv_data.to_csv(os.path.join(output_csv_path, "random_sampled_oasis_data.csv"), index=False)

if __name__ == "__main__":
    random_sample_oasis_data(PARSED_CSV_PATH, OUTPUT_DIR, NUM_SAMPLES_PER_GROUP)